#include "maps/SandboxPlacement.h"
#include <algorithm>
#include <array>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <zlib.h>
#include <iostream>
#include <stdexcept>
using namespace openemperor;
namespace {
constexpr std::size_t count=228U*228U;
constexpr maps::GridCell start{100,110};
std::size_t raw(maps::GridCell c){return std::size_t(c.y)*228U+c.x;}
void check(bool b,const char*m){if(!b)throw std::runtime_error(m);}
template<class F>void rejects(F f,const char*m){try{f();}catch(const std::invalid_argument&){return;}throw std::runtime_error(m);}
struct Fixture {
 maps::ParsedEmperorMap map;maps::MapGeometry geometry{170};maps::OriginalMapEntities entities;
 maps::StoredGraphicsPlan plan;std::vector<std::uint8_t> legacy=std::vector<std::uint8_t>(count,1);
 Fixture(){map.declared_map_size=170;map.terrain_raw.values.assign(count,0x80);map.objects_raw.values.assign(count,0);entities.manager_schema=1;entities.declared_map_size=170;plan.border=29;plan.height_bytes.assign(count,255);}
 maps::OriginalEntityRecord source(maps::GridCell p,unsigned id=7,unsigned index=0) const {
  maps::OriginalEntityRecord e;e.manager_index=index;e.original_id=maps::OriginalEntityId{id};e.serialized_original_id=int(id);e.status=3;e.local_x=std::int16_t(p.x-29);e.local_y=std::int16_t(p.y-29);e.serialized_cell_reference=int(raw(p));e.footprint_side=2;e.provenance.base_schema=4;return e;
 }
 void gate(int layout){auto e=source(start);e.entity_class=maps::OriginalEntityClass::GateHouse;e.type=130;e.footprint_side=1;e.gate_house=maps::OriginalGateHouseState{layout};e.provenance.wrapper_schema=1;e.provenance.extended_schema=1;e.provenance.class_wrapper_schema=2;entities.records.push_back(e);const unsigned w=layout?3:5,h=layout?5:3;for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x)map.terrain_raw.values[raw({start.x+x,start.y+y})]=0x8088;}
 auto make() const {return maps::make_sandbox_map_permissions(map,plan,geometry,legacy,entities);}
};
void free_and_protected(){Fixture f;f.legacy[raw(start)]=0;auto p=f.make();check(p->road_allowed({100,110})&&!p->building_allowed({100,110}),"road raw fact independent of legacy/render footprint");auto before=p->canonical_state();f.plan.assets.resize(2);f.plan.assets[0].status=maps::StoredStatus::DecodeFailed;f.plan.landscape_layers_available=false;f.plan.raw_saved_ids.assign(count,0xffffffff);f.plan.raw_candidate_bytes.assign(count,255);check(f.make()->canonical_state()==before,"decode/profile/saved graphic state cannot decide roads or passages");f.legacy[raw(start)]=1;auto e=f.source(start);f.entities.records.push_back(e);p=f.make();check(!p->road_allowed({100,110})&&!p->building_allowed({100,110})&&p->protected_original({100,110})&&p->road_blocker({101,111})==simulation::BuildBlocker::OriginalStructure,"complete original saved square reserved despite grass");check(p->road_allowed({102,112}),"original reservation does not expand beyond source square");Fixture rawbits;for(auto terrain:{4U,0x4080U,0x8088U,0x82U,0x2000080U,0x80080U}){rawbits.map.terrain_raw.values[raw(start)]=terrain;check(!rawbits.make()->road_allowed({100,110})&&!rawbits.make()->building_allowed({100,110}),"water/wall/gate/rock/pinnacle/offmap denied");}rawbits.map.terrain_raw.values[raw(start)]=0x80;rawbits.map.objects_raw.values[raw(start)]=1;check(!rawbits.make()->road_allowed({100,110}),"objects0 required");check(!f.make()->road_allowed({0,0}),"candidate-map border is not road terrain");}
void road_markings(){Fixture f;f.map.terrain_raw.values[raw(start)]=0xc0;auto p=f.make();check(p->road_allowed({100,110})&&!p->building_allowed({100,110})&&!p->fixed_passage({100,110}),"explicit ground-road raw marking permits paid roads only, not building or fixed road");f.map.objects_raw.values[raw(start)]=1;check(!f.make()->road_allowed({100,110}),"road-marked original objects stay blocked");for(auto value:{0x40U,0xc1U,0x1c0U,0x800c0U}){f.map.objects_raw.values[raw(start)]=0;f.map.terrain_raw.values[raw(start)]=value;check(!f.make()->road_allowed({100,110}),"ground-road whitelist admits no extra bits");}}
void passage_layouts(){for(int layout:{0,1}){Fixture f;f.gate(layout);auto p=f.make();check(p->gates().size()==1&&p->gates()[0].id==simulation::FixedGateId{7},"stable original gate ID is distinct and zero manager index valid");const std::array<simulation::Cell,3> corridor=layout?std::array<simulation::Cell,3>{{{100,112},{101,112},{102,112}}}:std::array<simulation::Cell,3>{{{102,110},{102,111},{102,112}}};const std::array<simulation::Cell,2> openings=layout?std::array<simulation::Cell,2>{{{99,112},{103,112}}}:std::array<simulation::Cell,2>{{{102,109},{102,113}}};check(p->gates()[0].corridor==std::vector(corridor.begin(),corridor.end())&&p->gates()[0].openings==openings,"literal independently authored short-axis corridor and two openings");for(auto c:p->gates()[0].protected_footprint)check(p->protected_original(c)&&!p->building_allowed(c),"all15 protected from buildings");for(unsigned k=0;k<3;++k)check(p->fixed_passage(corridor[k])&&p->road_allowed(corridor[k])&&p->cell_height(corridor[k])==-1,"exactthree corridor cells and signed height retained");check(p->transport_edge_allowed(openings[0],corridor[0])&&p->transport_edge_allowed(corridor[0],openings[0])&&p->transport_edge_allowed(openings[1],corridor[2])&&p->transport_edge_allowed(corridor[2],openings[1]),"both opening directions");check(p->transport_edge_allowed(corridor[0],corridor[1])&&p->transport_edge_allowed(corridor[1],corridor[2]),"ordinary internal neighbor edges");const simulation::Cell side=layout?simulation::Cell{101,111}:simulation::Cell{101,111};check(p->transport_edge_blocker(side,corridor[1])==simulation::BuildBlocker::GateSideEntry,"solid side entry denied");check(!p->road_allowed({100,110})&&p->road_blocker({100,110})==simulation::BuildBlocker::GateSolidPart,"solid gate corner denied independently of corridor");Fixture no_render=f;no_render.plan.height_bytes=f.plan.height_bytes;no_render.legacy.assign(count,0);auto missing=no_render.make();check(missing->gates()[0].corridor==p->gates()[0].corridor&&missing->road_mask()==p->road_mask(),"no render-derived legacy permissions prerequisite for gate/roads");}}
void markers(){for(int type:{162,163,174,180,185}){Fixture f;auto e=f.source(start);e.entity_class=maps::OriginalEntityClass::Industrial;e.type=std::int16_t(type);e.footprint_side=0;f.entities.records.push_back(e);auto second=e;second.manager_index=1;second.original_id=maps::OriginalEntityId{8};second.serialized_original_id=8;f.entities.records.push_back(second);auto p=f.make();check(p->protected_original({100,110})&&!p->road_allowed({100,110})&&p->road_allowed({101,110}),"bounded marker reserves only exact saved origin; duplicate markers are not duplicate physical claims");}Fixture bad;auto e=bad.source(start);e.entity_class=maps::OriginalEntityClass::Industrial;e.footprint_side=0;e.type=35;bad.entities.records.push_back(e);rejects([&]{bad.make();},"unknown zero-side marker must not free occupancy");Fixture other;other.gate(0);auto marker=other.source(start,8,1);marker.entity_class=maps::OriginalEntityClass::Industrial;marker.footprint_side=0;marker.type=163;other.entities.records.push_back(marker);rejects([&]{other.make();},"marker/gate conflict fail closed");}
void invalid_sources(){Fixture f;f.gate(0);auto mutate=[&](auto edit,const char* msg){auto bad=f;edit(bad);rejects([&]{bad.make();},msg);};mutate([](auto&b){b.map.terrain_raw.values[raw({104,112})]&=~8U;},"partial gate claims rejected");mutate([](auto&b){++b.entities.records[0].serialized_cell_reference;},"reference mismatch rejected");mutate([](auto&b){b.entities.records[0].gate_house->layout=2;},"unknown layout rejected");mutate([](auto&b){b.entities.records[0].provenance.class_wrapper_schema=3;},"unknown gate wrapper rejected");mutate([](auto&b){b.plan.height_bytes[raw({102,111})]=0;},"unequal corridor heights rejected");mutate([](auto&b){b.plan.height_bytes[raw({102,109})]=0;},"unequal opening height rejected");mutate([](auto&b){auto e=b.source({102,111},8,1);b.entities.records.push_back(e);},"overlapping original structure rejected");mutate([](auto&b){b.entities.manager_schema=0;},"unknown full manager schema rejected");mutate([](auto&b){b.plan.height_bytes.pop_back();},"truncated heights rejected");rejects([&]{maps::make_sandbox_map_permissions(f.map,f.plan,f.geometry,f.legacy,f.entities,2);},"unknown map policy rejected");Fixture h;h.plan.height_bytes[raw(start)]=128;h.plan.height_bytes[raw({101,110})]=127;auto p=h.make();check(p->cell_height({100,110})==-128&&p->cell_height({101,110})==127&&p->transport_edge_blocker({100,110},{101,110})==simulation::BuildBlocker::UnsupportedHeightTransition,"signed byte extremes do not create steep edges");}
void standalone_reader(){
 Fixture f;f.gate(1);
 using Bytes=std::vector<std::uint8_t>;
 const auto put16=[](Bytes&b,std::size_t p,unsigned v){b.at(p)=std::uint8_t(v);b.at(p+1)=std::uint8_t(v>>8);};
 const auto put32=[&](Bytes&b,std::size_t p,unsigned v){put16(b,p,v);put16(b,p+2,v>>16);};
 const auto append32=[&](Bytes&b,unsigned v){auto p=b.size();b.resize(p+4);put32(b,p,v);};
 Bytes record(6,0);put16(record,0,1);put32(record,2,1);
 const std::string name="cGateHouse";auto p=record.size();record.resize(p+6+name.size());put16(record,p,0xffff);put16(record,p+4,unsigned(name.size()));std::copy(name.begin(),name.end(),record.begin()+std::ptrdiff_t(p+6));
 p=record.size();record.resize(p+181+2+128+10);put16(record,p,4);record[p+2]=3;record[p+5]=1;
 put16(record,p+8,71);put16(record,p+10,81);put32(record,p+12,unsigned(raw(start)));put16(record,p+16,130);put32(record,p+112,1);put32(record,p+161,7);put16(record,p+181,1);put16(record,p+183,1);put16(record,p+311,2);
 Bytes bytes(std::size_t(maps::original_entities_logical_offset)+record.size(),0);
 const std::array<std::uint8_t,8> signature{5,0,0xfe,0xca,0,0,2,0};std::copy(signature.begin(),signature.end(),bytes.begin());put32(bytes,84,170);
 for(std::size_t k=0;k<count;++k){put32(bytes,std::size_t(maps::terrain_logical_offset)+k*4,f.map.terrain_raw.values[k]);put32(bytes,std::size_t(maps::objects_logical_offset)+k*4,f.map.objects_raw.values[k]);bytes[989275+k]=f.plan.height_bytes[k];}
 std::copy(record.begin(),record.end(),bytes.begin()+std::ptrdiff_t(maps::original_entities_logical_offset));
 Bytes container;append32(container,0xfedcbaaa);
 for(std::size_t at=0;at<bytes.size();at+=16384){const auto len=std::min<std::size_t>(16384,bytes.size()-at);uLongf length=compressBound(uLong(len));Bytes compressed(length);check(compress2(compressed.data(),&length,bytes.data()+at,uLong(len),6)==Z_OK,"authored map compression");compressed.resize(length);append32(container,0);append32(container,unsigned(length));append32(container,unsigned(len));container.insert(container.end(),compressed.begin(),compressed.end());}
 const auto root=std::filesystem::temp_directory_path()/("openemperor-map-permissions-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));
 struct Clean{std::filesystem::path root;~Clean(){std::error_code e;std::filesystem::remove_all(root,e);}}clean{root};std::filesystem::create_directories(root/"Cities");
 {std::ofstream out(root/"Cities/authored.map",std::ios::binary);out.write(reinterpret_cast<const char*>(container.data()),std::streamsize(container.size()));check(bool(out),"authored map file");}
 auto read=maps::read_sandbox_map_permissions(root,"Cities/authored.map",f.legacy);check(read->canonical_state()==f.make()->canonical_state(),"SDL-free contained reader and explicit typed full-manager builder produce identical topology");
 rejects([&]{maps::read_sandbox_map_permissions(root,"Cities/missing.map",f.legacy,2);},"unknown policy rejected before reading a missing file");
}
void legacy_contract(){Fixture f;maps::StoredCell c;c.storage=start;c.cell_index=raw(start);c.terrain_raw=0x80;c.objects_raw=0;c.footprint_index=0;c.status=maps::StoredStatus::Rendered;f.plan.cells.push_back(c);maps::PlacedFootprint fp;fp.origin=start;fp.width_cells=fp.height_cells=1;fp.status=maps::StoredStatus::Rendered;f.plan.footprints.push_back(fp);check(maps::make_sandbox_buildable_mask(f.plan,f.geometry)[raw(start)]==1,"legacy successful1x1 rendered fixture");f.plan.cells[0].status=maps::StoredStatus::DecodeFailed;check(maps::make_sandbox_buildable_mask(f.plan,f.geometry)[raw(start)]==0,"legacy decode dependence remains exact");f.plan.cells[0].status=maps::StoredStatus::Rendered;f.plan.footprints[0].width_cells=2;check(maps::make_sandbox_buildable_mask(f.plan,f.geometry)[raw(start)]==0,"legacy footprint dependence remains exact");}
}
int main(){try{free_and_protected();road_markings();passage_layouts();markers();invalid_sources();standalone_reader();legacy_contract();std::cout<<"Sandbox map permission tests passed\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
