# CMake generated Testfile for 
# Source directory: /Users/oli/github/OpenEmperor
# Build directory: /Users/oli/github/OpenEmperor/build-gate-passages
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("great-wall-dependency-paths" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-great-wall-dependency-paths-tests")
set_tests_properties("great-wall-dependency-paths" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;276;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("originalmapentities" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-originalmapentities-tests")
set_tests_properties("originalmapentities" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;282;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("greatwallmodels" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-greatwallmodels-tests")
set_tests_properties("greatwallmodels" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;282;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("greatwallselector" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-greatwallselector-tests")
set_tests_properties("greatwallselector" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;282;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("greatwallpresentation" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-greatwallpresentation-tests")
set_tests_properties("greatwallpresentation" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;282;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("landscape-selectors" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-landscape-selector-tests")
set_tests_properties("landscape-selectors" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;287;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("pinnacle-selectors" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-pinnacle-selector-tests")
set_tests_properties("pinnacle-selectors" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;291;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("wall-topology" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-wall-topology-tests")
set_tests_properties("wall-topology" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;295;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("landscape-instances" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-landscape-instance-tests")
set_tests_properties("landscape-instances" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;299;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-simulation" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-simulation-tests")
set_tests_properties("sandbox-simulation" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;303;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-production-chain" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-production-tests")
set_tests_properties("sandbox-production-chain" PROPERTIES  TIMEOUT "20" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;307;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("health-post-fallback-presentation" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-health-fallback-tests")
set_tests_properties("health-post-fallback-presentation" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;314;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("well-fallback-pixels" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-well-fallback-tests")
set_tests_properties("well-fallback-pixels" PROPERTIES  TIMEOUT "20" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;320;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v15-view" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-view-tests" "--health-only")
set_tests_properties("sandbox-city-v15-view" PROPERTIES  TIMEOUT "240" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;332;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("road-continuity-production-pixels" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-view-tests" "--road-continuity-only")
set_tests_properties("road-continuity-production-pixels" PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;333;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-geometry-view" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-view-tests" "--geometry16-only")
set_tests_properties("sandbox-city-v16-geometry-view" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;335;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-view" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-view-tests" "--maintenance-only")
set_tests_properties("sandbox-city-v16-view" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;336;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v14-view" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-view-tests" "--water-only")
set_tests_properties("sandbox-city-v14-view" PROPERTIES  TIMEOUT "240" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;338;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-software-view" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-view-tests")
set_tests_properties("sandbox-software-view" PROPERTIES  TIMEOUT "240" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;340;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("menu-session-flow" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-menu-session-tests")
set_tests_properties("menu-session-flow" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;352;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("input-coordinate-contract" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-input-coordinate-tests")
set_tests_properties("input-coordinate-contract" PROPERTIES  TIMEOUT "20" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;359;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("input-diagnostics-bounded" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-input-diagnostics-tests")
set_tests_properties("input-diagnostics-bounded" PROPERTIES  TIMEOUT "20" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;366;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("menu-input-boundaries" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-menu-input-tests")
set_tests_properties("menu-input-boundaries" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;379;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("map-input-boundaries" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-map-input-tests")
set_tests_properties("map-input-boundaries" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;387;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-input-reliability" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-view-tests" "--input-only")
set_tests_properties("sandbox-input-reliability" PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;390;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-map-permissions" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-map-permissions-tests")
set_tests_properties("sandbox-map-permissions" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;400;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-fixed-gate-passages" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-gate-passage-tests")
set_tests_properties("sandbox-fixed-gate-passages" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;403;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("gate-passage-road-preview" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-gate-passage-road-view-tests")
set_tests_properties("gate-passage-road-preview" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;406;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("gate-passage-save-recovery" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-gate-passage-save-tests")
set_tests_properties("gate-passage-save-recovery" PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;409;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-save-resume" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-save-tests")
set_tests_properties("sandbox-save-resume" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;413;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("autosave-recovery-history" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-recovery-tests")
set_tests_properties("autosave-recovery-history" PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;418;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-live-rerouting" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-routing-tests")
set_tests_properties("sandbox-live-rerouting" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;423;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-household-supply" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-household-tests")
set_tests_properties("sandbox-household-supply" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;428;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-settlement-distribution" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-settlement-tests")
set_tests_properties("sandbox-settlement-distribution" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;433;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-industry-production" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-industry-tests")
set_tests_properties("sandbox-industry-production" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;438;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-economy" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-tests")
set_tests_properties("sandbox-city-economy" PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;443;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v7-food" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v7-tests")
set_tests_properties("sandbox-city-v7-food" PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;449;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v8-service" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v8-tests")
set_tests_properties("sandbox-city-v8-service" PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;454;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v9-population" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v9-tests")
set_tests_properties("sandbox-city-v9-population" PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;460;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v10-scaling" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v10-tests")
set_tests_properties("sandbox-city-v10-scaling" PROPERTIES  TIMEOUT "600" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;465;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v11-markets" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v11-tests")
set_tests_properties("sandbox-city-v11-markets" PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;470;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v11-balance" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v11-balance-tests")
set_tests_properties("sandbox-city-v11-balance" PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;478;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v11-operation-controls" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v11-operations-tests")
set_tests_properties("sandbox-city-v11-operation-controls" PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;487;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v11-demolition" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v11-demolition-tests")
set_tests_properties("sandbox-city-v11-demolition" PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;494;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v12-base" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v12-tests" "base")
set_tests_properties("sandbox-city-v12-base" PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;500;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v12-persistence" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v12-tests" "persistence")
set_tests_properties("sandbox-city-v12-persistence" PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;500;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v12-determinism" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v12-tests" "determinism")
set_tests_properties("sandbox-city-v12-determinism" PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;500;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v12-endurance" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v12-tests" "endurance")
set_tests_properties("sandbox-city-v12-endurance" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;500;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v13-base" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v13-tests" "base")
set_tests_properties("sandbox-city-v13-base" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;510;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v13-persistence" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v13-tests" "persistence")
set_tests_properties("sandbox-city-v13-persistence" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;510;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v13-districts" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v13-tests" "districts")
set_tests_properties("sandbox-city-v13-districts" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;510;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v13-determinism" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v13-tests" "determinism")
set_tests_properties("sandbox-city-v13-determinism" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;510;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v13-endurance" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v13-tests" "endurance")
set_tests_properties("sandbox-city-v13-endurance" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;510;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v14-base" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v14-tests" "base")
set_tests_properties("sandbox-city-v14-base" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;519;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v14-persistence" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v14-tests" "persistence")
set_tests_properties("sandbox-city-v14-persistence" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;519;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v14-districts" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v14-tests" "districts")
set_tests_properties("sandbox-city-v14-districts" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;519;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v14-determinism" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v14-tests" "determinism")
set_tests_properties("sandbox-city-v14-determinism" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;519;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v14-endurance" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v14-tests" "endurance")
set_tests_properties("sandbox-city-v14-endurance" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;519;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v15-base" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v15-tests" "base")
set_tests_properties("sandbox-city-v15-base" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;528;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v15-persistence" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v15-tests" "persistence")
set_tests_properties("sandbox-city-v15-persistence" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;528;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v15-districts" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v15-tests" "districts")
set_tests_properties("sandbox-city-v15-districts" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;528;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v15-determinism" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v15-tests" "determinism")
set_tests_properties("sandbox-city-v15-determinism" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;528;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v15-endurance" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v15-tests" "endurance")
set_tests_properties("sandbox-city-v15-endurance" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;528;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-base" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v16-tests" "base")
set_tests_properties("sandbox-city-v16-base" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;537;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-persistence" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v16-tests" "persistence")
set_tests_properties("sandbox-city-v16-persistence" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;537;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-balance" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v16-tests" "balance")
set_tests_properties("sandbox-city-v16-balance" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;537;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-determinism" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v16-tests" "determinism")
set_tests_properties("sandbox-city-v16-determinism" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;537;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-endurance" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v16-tests" "endurance")
set_tests_properties("sandbox-city-v16-endurance" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;537;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-geometry" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v16-tests" "geometry")
set_tests_properties("sandbox-city-v16-geometry" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;537;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-determinism-v2" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v16-tests" "determinism-v2")
set_tests_properties("sandbox-city-v16-determinism-v2" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;537;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-city-v16-endurance-v2" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-city-v16-tests" "endurance-v2")
set_tests_properties("sandbox-city-v16-endurance-v2" PROPERTIES  TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;537;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("city-v11-start-guidance" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-city-start-guidance-tests")
set_tests_properties("city-v11-start-guidance" PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;547;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sandbox-courier-triage" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sandbox-courier-triage-tests")
set_tests_properties("sandbox-courier-triage" PROPERTIES  TIMEOUT "20" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;554;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("map-corpus-runner" "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "-m" "unittest" "discover" "-s" "/Users/oli/github/OpenEmperor/tests" "-p" "test_verify_map_corpus.py")
set_tests_properties("map-corpus-runner" PROPERTIES  ENVIRONMENT "PYTHONDONTWRITEBYTECODE=1" RUN_SERIAL "TRUE" TIMEOUT "20" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;563;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("resource-group-lookup" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-resource-group-tests")
set_tests_properties("resource-group-lookup" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;572;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("emperor-map-semantic-geometry" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-map-semantic-tests")
set_tests_properties("emperor-map-semantic-geometry" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;576;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("emperor-map-reader" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-map-tests")
set_tests_properties("emperor-map-reader" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;581;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("emperor-map-debug-view" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-map-view-tests")
set_tests_properties("emperor-map-debug-view" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;586;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("stored-graphics-map-preview" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-stored-graphics-tests")
set_tests_properties("stored-graphics-map-preview" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;593;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("ordinary-wall-gate-presentation" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-ordinary-wall-gate-tests")
set_tests_properties("ordinary-wall-gate-presentation" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;599;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("ordinary-gate-map-presentation" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-ordinary-gate-presentation-tests")
set_tests_properties("ordinary-gate-map-presentation" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;605;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("terrain-preview-bindings-geometry-render" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-terrain-preview-tests")
set_tests_properties("terrain-preview-bindings-geometry-render" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;610;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("scene-math-manifest" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-scene-tests")
set_tests_properties("scene-math-manifest" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;614;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("scene-renderer" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-scene-renderer-tests")
set_tests_properties("scene-renderer" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;620;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sg3-parser-bounds" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sg3-tests")
set_tests_properties("sg3-parser-bounds" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;624;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sg3-rgba-decode" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sg3-rgba-tests")
set_tests_properties("sg3-rgba-decode" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;629;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sg3-omega-decode" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sg3-omega-tests")
set_tests_properties("sg3-omega-decode" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;634;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sg3-alpha-decode" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sg3-alpha-tests")
set_tests_properties("sg3-alpha-decode" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;639;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sg3-alpha-audit" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sg3-alpha-audit-tests")
set_tests_properties("sg3-alpha-audit" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;644;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sg3-isometric-decode" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sg3-isometric-tests")
set_tests_properties("sg3-isometric-decode" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;649;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("sg3-image-loader" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-sg3-loader-tests")
set_tests_properties("sg3-image-loader" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;654;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("walker-visual-profile-pose-render" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-walker-visual-tests")
set_tests_properties("walker-visual-profile-pose-render" PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;660;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("building-visual-profile-depth" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-building-visual-tests")
set_tests_properties("building-visual-profile-depth" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;667;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("road-topology-live-preview" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-road-topology-tests")
set_tests_properties("road-topology-live-preview" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;673;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("road-responsive-preview-batch" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-road-responsiveness-tests")
set_tests_properties("road-responsive-preview-batch" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;679;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("frame-pacing-remainder" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-frame-pacing-tests")
set_tests_properties("frame-pacing-remainder" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;684;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("road-visual-profile-pixels" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-road-visual-tests")
set_tests_properties("road-visual-profile-pixels" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;691;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("compatibility-profile-fingerprints" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-compatibility-tests" "/Users/oli/github/OpenEmperor/build-gate-passages/resources")
set_tests_properties("compatibility-profile-fingerprints" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;696;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("unified-map-sandbox-pixels" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-unified-painter-tests")
set_tests_properties("unified-map-sandbox-pixels" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;702;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("scene-composition-production-pixels" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-scene-composition-tests")
set_tests_properties("scene-composition-production-pixels" PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;714;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("texture-compatibility-production-pixels" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-texture-compatibility-tests")
set_tests_properties("texture-compatibility-production-pixels" PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;722;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("texture-compatibility-sdl-pixels" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-texture-compatibility-sdl-tests")
set_tests_properties("texture-compatibility-sdl-pixels" PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;729;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("texture-preview-failure-alpha" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-texture-preview-failure-tests")
set_tests_properties("texture-preview-failure-alpha" PROPERTIES  TIMEOUT "20" _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;736;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("png-preview-bounds" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-png-preview-tests")
set_tests_properties("png-preview-bounds" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;742;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("asset-catalog" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-asset-catalog-tests")
set_tests_properties("asset-catalog" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;750;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("asset-browser-cache" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-asset-browser-tests")
set_tests_properties("asset-browser-cache" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;758;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
add_test("release-version" "/Users/oli/github/OpenEmperor/build-gate-passages/openemperor-version-tests")
set_tests_properties("release-version" PROPERTIES  _BACKTRACE_TRIPLES "/Users/oli/github/OpenEmperor/CMakeLists.txt;763;add_test;/Users/oli/github/OpenEmperor/CMakeLists.txt;0;")
